# Generated by Django 2.2.1 on 2020-09-10 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('login', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(default='', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('contacto1', models.CharField(max_length=13)),
                ('contacto2', models.CharField(blank=True, max_length=13)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=50)),
                ('disponibilidad', models.CharField(blank=True, max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('fechaejecucion', models.DateTimeField()),
                ('estadocliente', models.CharField(choices=[('No aplicable', 'no aplicable'), ('Confirmado', 'confirmado'), ('Sin Factibilidad', 'sin factibilidad'), ('Deuda cliente', 'deuda cliente'), ('Deuda domicilio', 'deuda domicilio'), ('Responsabilidad cliente', 'responsabilidad cliente'), ('Sin contacto', 'sin contacto'), ('Confirmado cuenta creada', 'confirmado cuenta creada')], default='No aplicable', max_length=30)),
                ('estadoticket', models.CharField(choices=[('No aplicable', 'no aplicable'), ('En proceso', 'en proceso'), ('Tecnico no acude', 'tecnico no acude'), ('Cerrado', 'cerrado'), ('Cerrado no terminado', 'cerrado no terminado')], default='No aplicable', max_length=30)),
                ('mediodepago', models.CharField(blank=True, max_length=30)),
                ('monto', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Client')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, max_length=12)),
                ('capacidad', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=300)),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking2createdat', to='api.Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking2created', to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('mac', models.CharField(blank=True, max_length=12)),
                ('pppoe', models.CharField(blank=True, max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Client')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='encargado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Technician'),
        ),
    ]
