# Generated by Django 2.2.1 on 2020-12-23 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='tracking_order',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking2created', to=settings.AUTH_USER_MODEL),
        ),
    ]
