# Generated by Django 2.2.1 on 2020-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='rut',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
