# Generated by Django 2.2.1 on 2020-09-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200910_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
