# Generated by Django 2.2.1 on 2020-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200910_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
