# Generated by Django 2.2.1 on 2020-09-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200911_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_residence',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Residence'),
        ),
    ]
