# Generated by Django 2.2.1 on 2021-01-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210129_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='valor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='estadocliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClientStatus'),
        ),
    ]
