# Generated by Django 2.2.1 on 2021-01-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210129_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='estadocliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClientStatus'),
        ),
    ]
