# Generated by Django 2.2.1 on 2020-12-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201223_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='tracking_order',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.ManyToManyField(blank=True, related_name='orders', to='api.Tracking'),
        ),
    ]
