# Generated by Django 2.2.1 on 2020-12-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201223_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking',
        ),
    ]
