# Generated by Django 2.2.1 on 2021-05-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20210309_1410'),
        ('api', '0075_auto_20210308_2114'),
    ]

    operations = [
    ]
